# Cheatsheet

This is a quick overview of the features and functions you could use during the exercises.

## Python stuff

Cells are expressions, so the last expression is the result of the cell. Print statements result in extra output.

In [1]:
print('hello')
'world'

hello


'world'

Multiple values can be assigned in 1 statement

In [2]:
a, b, c = 0, "a", -42.0
print(a, b, c)

0 a -42.0


Class members are accessable via `self.`

In [3]:
class Box(object):
    def __init__(self, value):
        self.value = value
    
    def get_value(self):
        return self.value

box = Box(42)
print(box.get_value())
print(box.value)

42
42


## NumPy

In [4]:
import numpy as np

Create a new array

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
a

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a.shape)
a

(2, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
print(a.shape[0])
print(a.shape[1])
print(a.shape[2])

2
2
3


Arrays with only zeroes or ones.

In [8]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Create a copy

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a
c = np.copy(a)
a[0,:] = 0
print(a)
print(b)
print(c)

[[0 0 0]
 [4 5 6]]
[[0 0 0]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Create random arrays

In [11]:
a = np.random.uniform(-0.5, 0.5, size=(2, 3))
print(a)
b = np.random.normal(0, 0.5, size=(2, 3))
print(b)

[[-0.2336023  -0.13891413  0.37818701]
 [-0.27483082 -0.49428612 -0.07936161]]
[[-0.22782505 -0.59749327  0.01588448]
 [-0.86553282  0.30013823  0.88736957]]


#### Operations

Scalars can be added to arrays

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a + 3)

[[4 5 6]
 [7 8 9]]


Vectors can be added to arrays row-by-row

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
print(a.shape, b.shape)
print(a + b)

(2, 3) (3,)
[[2 4 6]
 [5 7 9]]


Single row arrays can be added row-by-row

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3]])
print(a.shape, b.shape)
print(a + b)

(2, 3) (1, 3)
[[2 4 6]
 [5 7 9]]


Not correct shape for broadcast results in ValueError

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])
print(a.shape, b.shape)
print(a + b)

(2, 3) (2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

Arrays can be multiplied as matrices

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1], [2], [3]])
print(a)
print(b)
print()
print(a.shape, b.shape)
c = np.matmul(a, b)
print(c.shape)
c

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]]

(2, 3) (3, 1)
(2, 1)


array([[14],
       [32]])

Array can be multiplied element-wise

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[2, 3, 4], [5, 6, 7]])
print(a)
print(b)
print()
print(a.shape, b.shape)
c = a * b
print(c.shape)
c

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]

(2, 3) (2, 3)
(2, 3)


array([[ 2,  6, 12],
       [20, 30, 42]])

Transpose

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Select right axis

Sum everything

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.sum(a)
print(b.shape)
b

()


21

Sum column by column

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.sum(a, axis=0)
print(b.shape)
b

(3,)


array([5, 7, 9])

Sum row by row

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.sum(a, axis=1)
print(b.shape)
b

(2,)


array([ 6, 15])

Sum column by column but do not reduce number of dimensions.

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
b = np.sum(a, axis=0, keepdims=True)
print(b.shape)
b

(2, 3)
(1, 3)


array([[5, 7, 9]])

#### Filtering

Select only middle column.

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[:,2]

array([3, 6])

Select only a first two columns.

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[:,:2]

array([[1, 2],
       [4, 5]])

Values can be filtered

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
(a >= 3) & (a < 5)

array([[False, False,  True],
       [ True, False, False]])

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
~((a >= 3) & (a < 5))

array([[ True,  True, False],
       [False,  True,  True]])

Get values that are resulted in `True`

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[(a >= 3) & (a < 5)]

array([3, 4])

Change all values between 3 and 5 to 0

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[(a >= 3) & (a < 5)] = 0
a

array([[1, 2, 0],
       [0, 5, 6]])

Booleans and numbers can be mixed

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])
((a >= 3) & (a < 5)) * 1

array([[0, 0, 1],
       [1, 0, 0]])