In [5]:
import numpy as np
from siouxdnn import dense, relu, sigmoid, binary_cross_entropy_loss
from siouxdnn import dense_backward, relu_backward, sigmoid_backward, binary_cross_entropy_loss_backward

# ReLU

In [22]:
y_true = (np.random.uniform(0, 1, size=(3, 1)) >= 0.5)*1

z1 = np.random.uniform(-1, 1, size=(3, 4))
w2 = np.random.uniform(-1, 1, size=(4, 1))
b2 = np.random.uniform(-1, 1, size=(1, 1))

a1 = relu(z1)
z2 = dense(a1, w2, b2)
y_pred = sigmoid(z2)
loss = binary_cross_entropy_loss(y_true, y_pred)
dy_pred = binary_cross_entropy_loss_backward(y_true, y_pred)
dz2 = sigmoid_backward(z2, dy_pred)
dw2, db2, da1 = dense_backward(a1, dz2, w2)
dz1 = relu_backward(z1, da1)

print(f'z = np.array({np.array2string(z1, separator=",")})')
print(f'da = np.array({np.array2string(da1, separator=",")})')
print(dz1)

z = np.array([[-0.3841685 , 0.96313277, 0.01752332, 0.70375869],
 [-0.90051653, 0.36881432,-0.87937234,-0.07766394],
 [ 0.99909255,-0.28151873, 0.21100903, 0.96628448]])
da = np.array([[ 0.10135023,-0.09567351, 0.00798541, 0.01288583],
 [ 0.12338271,-0.11647193, 0.00972135, 0.01568707],
 [ 0.18808731,-0.17755236, 0.01481944, 0.02391371]])
[[ 0.         -0.09567351  0.00798541  0.01288583]
 [ 0.         -0.11647193  0.          0.        ]
 [ 0.18808731  0.          0.01481944  0.02391371]]


# Sigmoid

In [27]:
y_true = (np.random.uniform(0, 1, size=(3, 1)) >= 0.5)*1

z1 = np.random.uniform(-1, 1, size=(3, 4))
w2 = np.random.uniform(-1, 1, size=(4, 1))
b2 = np.random.uniform(-1, 1, size=(1, 1))

a1 = sigmoid(z1)
z2 = dense(a1, w2, b2)
y_pred = sigmoid(z2)
loss = binary_cross_entropy_loss(y_true, y_pred)
dy_pred = binary_cross_entropy_loss_backward(y_true, y_pred)
dz2 = sigmoid_backward(z2, dy_pred)
dw2, db2, da1 = dense_backward(a1, dz2, w2)
dz1 = sigmoid_backward(z1, da1)

print(f'z = np.array({np.array2string(z1, separator=",")})')
print(f'da = np.array({np.array2string(da1, separator=",")})')
print(dz1)

z = np.array([[ 0.90145683, 0.35448664, 0.12282405, 0.14473946],
 [ 0.90185776,-0.83611207,-0.74306445, 0.75256026],
 [-0.68165728, 0.46613136, 0.22696806,-0.34379635]])
da = np.array([[ 0.09298582,-0.13436976, 0.02718292, 0.02473067],
 [-0.12145152, 0.17550431,-0.03550441,-0.03230145],
 [-0.15272906, 0.22070212,-0.0446479 ,-0.04062008]])
[[ 0.01909686 -0.03255884  0.00677016  0.0061504 ]
 [-0.02493875  0.03702021 -0.0077554  -0.00703186]
 [-0.03406903  0.0522837  -0.01101945 -0.00986076]]


# Dense

In [77]:
y_true = (np.random.uniform(0, 1, size=(3, 1)) >= 0.5)*1

a0 = np.random.uniform(-1, 1, size=(3, 4))
w1 = np.random.uniform(-1, 1, size=(4, 5))
b1 = np.random.uniform(-1, 1, size=(1, 5))
w2 = np.random.uniform(-1, 1, size=(5, 1))
b2 = np.random.uniform(-1, 1, size=(1, 1))

z1 = dense(a0, w1, b1)
a1 = relu(z1)
z2 = dense(a1, w2, b2)
a2 = sigmoid(z2)

loss = binary_cross_entropy_loss(y_true, a2)
da2 = binary_cross_entropy_loss_backward(y_true, a2)

dz2 = sigmoid_backward(z2, da2)
dw2, db2, da1 = dense_backward(a1, dz2, w2)

dz1 = relu_backward(z1, da1)
dw1, db1, da0 = dense_backward(a0, dz1, w1)

print(f'a_prev = np.array({np.array2string(a0, separator=",")})')
print(f'dz = np.array({np.array2string(dz1, separator=",")})')
print(f'w = np.array({np.array2string(w1, separator=",")})')

print(dw1)
print(db1)
print(da0)

a_prev = np.array([[ 0.35375751,-0.3776729 , 0.32942281,-0.27827347],
 [-0.93693319,-0.085921  , 0.01547009, 0.80320843],
 [-0.74478941, 0.22313203,-0.21071294, 0.86850543]])
dz = np.array([[ 0.        , 0.03582932, 0.        , 0.05249304,-0.08647048],
 [ 0.04884253, 0.06242368, 0.11415199, 0.09145607, 0.        ],
 [ 0.04169974, 0.05329477, 0.09745826, 0.07808142, 0.        ]])
w = np.array([[-0.89889975,-0.47854249,-0.52593611,-0.90020105, 0.63363267],
 [ 0.14985559,-0.36020986,-0.85147906,-0.68566762, 0.1925108 ],
 [-0.54756299, 0.80574929,-0.81764706,-0.4837164 , 0.66329728],
 [-0.6358417 ,-0.13549578,-0.08654791, 0.03401955,-0.01993571]])
[[-0.07681971 -0.08550531 -0.17953867 -0.12527264 -0.03058958]
 [ 0.00510795 -0.0070035   0.01193801 -0.01026073  0.03265756]
 [-0.00803108  0.0015388  -0.01876978  0.00225447 -0.02848535]
 [ 0.07544718  0.08645567  0.17633087  0.12666501  0.02406244]]
[[ 0.09054227  0.15154777  0.21161025  0.22203054 -0.08647048]]
[[-0.11919067 -0.06554536 -0.05